// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import EntryTypeController from "./entry_type_controller"
application.register("entry-type", EntryTypeController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ShortcutController from "./shortcut_controller"
application.register("shortcut", ShortcutController)

import TxnNavController from "./txn_nav_controller"
application.register("txn-nav", TxnNavController)
